/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bms;

import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author shona
 */
public class signup2 extends javax.swing.JFrame {

    int formno;
    public signup2() {
        initComponents();

    }
    public signup2(int formno) {
        this.formno=formno;
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(SAButton);
        group.add(CAButton);
        group.add(FButton);
        group.add(RButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SAButton = new javax.swing.JRadioButton();
        CAButton = new javax.swing.JRadioButton();
        FButton = new javax.swing.JRadioButton();
        RButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        atmCheckBox = new javax.swing.JCheckBox();
        mbCheckBox = new javax.swing.JCheckBox();
        ibCheckBox = new javax.swing.JCheckBox();
        smsCheckBox = new javax.swing.JCheckBox();
        chequeCheckBox = new javax.swing.JCheckBox();
        eCheckBox = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        bankTextField = new javax.swing.JTextField();
        branchTextField = new javax.swing.JTextField();
        codeTextField = new javax.swing.JTextField();
        cardTextField = new javax.swing.JTextField();
        pinTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("2. Bank Account Details");

        jLabel2.setText("Account Type     :");

        SAButton.setText("Saving Account");
        SAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAButtonActionPerformed(evt);
            }
        });

        CAButton.setText("Current Account");

        FButton.setText("Fixed Account Button");

        RButton.setText("Recurring Deposit Account");

        jLabel3.setText("Bank Name         :");

        jLabel4.setText("Branch Name      :");

        jLabel5.setText("Branch Code       :");

        jLabel6.setText("CARD NO          :");

        jLabel7.setText("PIN                    :");

        jLabel8.setText("Services Required");

        atmCheckBox.setText("ATM card");

        mbCheckBox.setText("Mobile Banking");

        ibCheckBox.setText("Internet Banking");
        ibCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibCheckBoxActionPerformed(evt);
            }
        });

        smsCheckBox.setText("E-mail / SMS alerts");

        chequeCheckBox.setText("chequeBook");

        eCheckBox.setText("e-Statement");

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jCheckBox7.setText("I hereby declare that the above information is true and correct to the best of my knowledge");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cardTextField.setText("xxxx xxxx xxxx xxxx");

        pinTextField.setText("xxxx");
        pinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atmCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mbCheckBox)
                            .addComponent(chequeCheckBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bankTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                    .addComponent(branchTextField)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CAButton))
                            .addGap(70, 70, 70)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RButton)
                                .addComponent(FButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ibCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(smsCheckBox)
                                .addComponent(eCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(branchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FButton)
                    .addComponent(SAButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RButton)
                    .addComponent(CAButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atmCheckBox)
                    .addComponent(ibCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mbCheckBox)
                    .addComponent(smsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chequeCheckBox)
                    .addComponent(eCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jCheckBox7)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAButtonActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String bank = bankTextField.getText();
        String branch = branchTextField.getText();
        String code = codeTextField.getText();
        String type=null;
        if(SAButton.isSelected()){
            type="Saving Account";
        }else if(CAButton.isSelected()){
            type="Current Account";
        }
        else if(FButton.isSelected()){
            type="Fixed Deposit Account";
        }
        else if(RButton.isSelected()){
            type="Recurring Deposit Account";
        }
        Random random = new Random();
        long cardNumberBase = 5040936000000000L;
        long cardNumberSuffix = (long)(random.nextDouble() * 1_0000_0000L); // 8 digits
        String cardnumber = String.valueOf(cardNumberBase + cardNumberSuffix);

        int pin = 1000 + random.nextInt(9000);
        String pinnumber = String.valueOf(pin);

        String facility = "";
                if(atmCheckBox.isSelected()){
                    facility += "ATM Card, ";
                }
                if (ibCheckBox.isSelected()){
                    facility += "Internet Banking, ";
                }
                if (mbCheckBox.isSelected()){
                    facility += "Mobile Banking, ";
                }
                if (smsCheckBox.isSelected()){
                    facility += "E-mail / SMS alerts, ";
                }
                if (chequeCheckBox.isSelected()){
                    facility += "ChequeBook, ";
                }
                if (eCheckBox.isSelected()){
                    facility += "e-Statements, ";
                }

                if(facility.length() > 0) {
                    facility = facility.substring(0, facility.length() - 2); // remove last comma and space
                }

                System.out.println("Submit clicked!");

        
        try {
    if (type == null) {
        JOptionPane.showMessageDialog(null,"Account type is required.");
        return;
    }
    if (!jCheckBox7.isSelected()) {
        JOptionPane.showMessageDialog(null,"Please accept the declaration.");
        return;
    }
    DBconnection c = new DBconnection();
    String query = "INSERT INTO signup2 (bank, branch, code, account_type, card_number, pin_number, facilities, balance) VALUES ('"
        + bank + "', '" + branch + "', '" + code + "', '" + type + "', '" 
        + cardnumber + "', '" + pinnumber + "', '" + facility + "', 0.0)";
    c.s.executeUpdate(query);
    JOptionPane.showMessageDialog(null,"Account created successfully!\nCard No: " + cardnumber + "\nPIN: " + pinnumber);
    c.s.close();
    } 
    catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
    }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void ibCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibCheckBoxActionPerformed

    private void pinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CAButton;
    private javax.swing.JRadioButton FButton;
    private javax.swing.JRadioButton RButton;
    private javax.swing.JRadioButton SAButton;
    private javax.swing.JCheckBox atmCheckBox;
    private javax.swing.JTextField bankTextField;
    private javax.swing.JTextField branchTextField;
    private javax.swing.JTextField cardTextField;
    private javax.swing.JCheckBox chequeCheckBox;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JCheckBox eCheckBox;
    private javax.swing.JCheckBox ibCheckBox;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox mbCheckBox;
    private javax.swing.JTextField pinTextField;
    private javax.swing.JCheckBox smsCheckBox;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
